import { Clock3, Lightbulb, Microscope } from "lucide-react";

export function AssistantSidebar({ recentQuestions, suggestedQuestions, researchAreas, activeArea, onAsk, onAreaChange, onClearRecent }: { recentQuestions: string[]; suggestedQuestions: string[]; researchAreas: string[]; activeArea: string; onAsk: (question: string) => void; onAreaChange: (area: string) => void; onClearRecent: () => void }) {
  return <aside className="space-y-4 lg:sticky lg:top-24 lg:self-start" aria-label="Research assistant navigation">
    <section className="rounded-3xl border border-border/70 bg-card/70 p-5"><div className="flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-primary"><Clock3 aria-hidden="true" className="size-4" /> Recent questions</h2>{recentQuestions.length > 0 && <button type="button" onClick={onClearRecent} className="text-xs text-muted-foreground underline-offset-4 hover:text-foreground hover:underline">Clear</button>}</div>{recentQuestions.length > 0 ? <ul className="mt-4 space-y-1">{recentQuestions.map((question) => <li key={question}><button type="button" onClick={() => onAsk(question)} className="w-full rounded-xl px-3 py-2.5 text-left text-sm leading-snug text-muted-foreground transition-colors hover:bg-accent hover:text-foreground">{question}</button></li>)}</ul> : <p className="mt-4 text-sm leading-relaxed text-muted-foreground">Questions asked on this device will appear here.</p>}</section>
    <section className="rounded-3xl border border-border/70 bg-card/70 p-5"><h2 className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-primary"><Lightbulb aria-hidden="true" className="size-4" /> Suggested questions</h2><ul className="mt-4 space-y-1">{suggestedQuestions.slice(0, 4).map((question) => <li key={question}><button type="button" onClick={() => onAsk(question)} className="w-full rounded-xl px-3 py-2.5 text-left text-sm leading-snug text-muted-foreground transition-colors hover:bg-accent hover:text-foreground">{question}</button></li>)}</ul></section>
    <section className="rounded-3xl border border-border/70 bg-card/70 p-5"><h2 className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-primary"><Microscope aria-hidden="true" className="size-4" /> Research areas</h2><div className="mt-4 flex flex-wrap gap-2">{["All", ...researchAreas].map((area) => <button key={area} type="button" aria-pressed={activeArea === area} onClick={() => onAreaChange(area)} className="rounded-full border border-border/70 px-3 py-1.5 text-xs font-medium text-muted-foreground transition-colors hover:border-primary/30 hover:text-foreground aria-pressed:border-primary/40 aria-pressed:bg-primary/10 aria-pressed:text-primary">{area}</button>)}</div></section>
  </aside>;
}
