"use client";

import { Activity, ChartNoAxesCombined, GitBranch, Network } from "lucide-react";
import { useMemo, useState } from "react";
import publicationData from "@/data/synced/publications.json";
import repositoryData from "@/data/synced/github-repositories.json";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import type { Publication, Repository } from "@/types/research";

const publications = publicationData as Publication[];
const repositories = repositoryData as unknown as Repository[];
const views = [
  { id: "overview", label: "Overview", icon: ChartNoAxesCombined },
  { id: "evolution", label: "Evolution", icon: Activity },
  { id: "network", label: "Research network", icon: Network },
  { id: "activity", label: "Research activity", icon: GitBranch },
] as const;
type View = typeof views[number]["id"];

const countBy = (values: string[]) => [...values.reduce((counts, value) => counts.set(value, (counts.get(value) ?? 0) + 1), new Map<string, number>())].sort((left, right) => right[1] - left[1]);
const recentYears = [...new Set(publications.map((publication) => publication.year).filter((year): year is number => year !== null))].sort((a, b) => a - b).slice(-12);
const yearCounts = recentYears.map((year) => ({ year, count: publications.filter((publication) => publication.year === year).length }));
const maxYearCount = Math.max(...yearCounts.map(({ count }) => count), 1);
const typeCounts = countBy(publications.map((publication) => publication.type));
const areaCounts = countBy(publications.flatMap((publication) => publication.researchAreas));
const publisherCounts = countBy(publications.map((publication) => publication.publisher).filter((publisher): publisher is string => Boolean(publisher))).slice(0, 7);
const venueCounts = countBy(publications.map((publication) => publication.venue).filter((venue): venue is string => Boolean(venue))).slice(0, 7);
const keywordCounts = countBy(publications.flatMap((publication) => publication.keywords.map((keyword) => keyword.trim())).filter(Boolean)).slice(0, 36);

function RankedBars({ title, data }: { title: string; data: Array<[string, number]> }) {
  const max = Math.max(...data.map(([, count]) => count), 1);
  return <Card><CardContent className="p-6 sm:p-7"><h3 className="font-display text-2xl">{title}</h3><div className="mt-7 space-y-4">{data.map(([label, count]) => <div key={label}><div className="mb-1.5 flex items-end justify-between gap-4 text-sm"><span className="line-clamp-1">{label}</span><span className="font-semibold text-primary">{count}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary/75" style={{ width: `${Math.max((count / max) * 100, 4)}%` }} /></div></div>)}</div></CardContent></Card>;
}

function Timeline() {
  return <Card className="md:col-span-2"><CardContent className="p-6 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Year-wise output</p><h3 className="mt-3 font-display text-3xl">Publication timeline</h3></div><p className="text-sm text-muted-foreground">ORCID activity · latest {recentYears.length} years</p></div><div className="mt-10 flex h-64 items-end gap-2 border-b border-border/70 sm:gap-4" role="img" aria-label={`Publication counts by year: ${yearCounts.map(({ year, count }) => `${year}: ${count}`).join(", ")}`}>{yearCounts.map(({ year, count }) => <div key={year} className="group flex h-full min-w-0 flex-1 flex-col items-center justify-end"><span className="mb-2 text-xs font-semibold text-primary opacity-0 transition-opacity group-hover:opacity-100 group-focus-within:opacity-100">{count}</span><div className="w-full max-w-12 rounded-t-lg bg-primary/75 transition-colors group-hover:bg-primary" style={{ height: `${Math.max((count / maxYearCount) * 85, 3)}%` }} /><span className="mt-3 -rotate-45 text-[.65rem] text-muted-foreground sm:rotate-0 sm:text-xs">{year}</span></div>)}</div></CardContent></Card>;
}

function Evolution() {
  const maxAreaYear = Math.max(...areaCounts.flatMap(([area]) => recentYears.map((year) => publications.filter((publication) => publication.year === year && publication.researchAreas.includes(area)).length)), 1);
  const monthCells = recentYears.slice(-6).flatMap((year) => Array.from({ length: 12 }, (_, month) => ({ year, month, count: publications.filter((publication) => publication.publicationDate && Number(publication.publicationDate.slice(0, 4)) === year && Number(publication.publicationDate.slice(5, 7)) === month + 1).length })));
  const maxMonth = Math.max(...monthCells.map(({ count }) => count), 1);
  return <div className="grid gap-5"><Card><CardContent className="overflow-x-auto p-6 sm:p-8"><h3 className="font-display text-3xl">Research evolution</h3><p className="mt-2 text-sm text-muted-foreground">Area intensity across the publication timeline.</p><div className="mt-8 min-w-[44rem] space-y-3">{areaCounts.slice(0, 8).map(([area]) => <div key={area} className="grid grid-cols-[12rem_1fr] items-center gap-4"><span className="text-sm font-medium">{area}</span><div className="grid gap-1" style={{ gridTemplateColumns: `repeat(${recentYears.length}, minmax(1.5rem, 1fr))` }}>{recentYears.map((year) => { const count = publications.filter((publication) => publication.year === year && publication.researchAreas.includes(area)).length; return <div key={year} title={`${area}, ${year}: ${count}`} className="aspect-square rounded-md border border-primary/10" style={{ backgroundColor: `hsl(var(--primary) / ${count ? Math.max(count / maxAreaYear, .12) : .025})` }}><span className="sr-only">{year}: {count}</span></div>; })}</div></div>)}</div></CardContent></Card><Card><CardContent className="overflow-x-auto p-6 sm:p-8"><h3 className="font-display text-3xl">Publication heatmap</h3><p className="mt-2 text-sm text-muted-foreground">Monthly publication activity for the latest six recorded years.</p><div className="mt-8 min-w-[44rem] space-y-2">{recentYears.slice(-6).map((year) => <div key={year} className="grid grid-cols-[4rem_1fr] items-center gap-3"><span className="text-xs font-semibold text-muted-foreground">{year}</span><div className="grid grid-cols-12 gap-1.5">{monthCells.filter((cell) => cell.year === year).map(({ month, count }) => <div key={month} title={`${new Intl.DateTimeFormat("en", { month: "long" }).format(new Date(2024, month))} ${year}: ${count}`} className="aspect-square rounded-md border border-primary/10" style={{ backgroundColor: `hsl(var(--primary) / ${count ? Math.max(count / maxMonth, .14) : .025})` }}><span className="sr-only">Month {month + 1}: {count}</span></div>)}</div></div>)}</div></CardContent></Card><Card><CardContent className="p-6 sm:p-8"><h3 className="font-display text-3xl">Keyword cloud</h3><p className="mt-2 text-sm text-muted-foreground">Recurring concepts extracted from enriched publication metadata.</p><div className="mt-8 flex flex-wrap items-baseline gap-x-5 gap-y-3">{keywordCounts.map(([keyword, count], index) => <span key={keyword} className="leading-none text-primary" style={{ fontSize: `${Math.max(1, 2.15 - index * .035)}rem`, opacity: Math.max(.48, 1 - index * .018) }} title={`${count} publications`}>{keyword}</span>)}</div></CardContent></Card></div>;
}

function ResearchNetwork() {
  const areas = areaCounts.slice(0, 8).map(([area]) => area);
  const positions = [[100, 150], [250, 65], [430, 75], [600, 155], [525, 310], [340, 345], [155, 320], [350, 205]];
  const edges = areas.flatMap((left, leftIndex) => areas.slice(leftIndex + 1).map((right, offset) => ({ left, right, leftIndex, rightIndex: leftIndex + offset + 1, count: publications.filter((publication) => publication.researchAreas.includes(left) && publication.researchAreas.includes(right)).length }))).filter(({ count }) => count > 0);
  const maxEdge = Math.max(...edges.map(({ count }) => count), 1);
  return <div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><Card><CardContent className="p-4 sm:p-8"><h3 className="font-display text-3xl">Research network</h3><p className="mt-2 text-sm text-muted-foreground">Co-occurrence of research areas across publications.</p><svg className="mt-6 h-auto w-full" viewBox="0 0 700 410" role="img" aria-labelledby="network-title network-description"><title id="network-title">Research area network</title><desc id="network-description">Connections show research areas that occur together in publication records.</desc>{edges.map((edge) => <line key={`${edge.left}-${edge.right}`} x1={positions[edge.leftIndex][0]} y1={positions[edge.leftIndex][1]} x2={positions[edge.rightIndex][0]} y2={positions[edge.rightIndex][1]} stroke="hsl(var(--primary))" strokeOpacity={.13 + (edge.count / maxEdge) * .35} strokeWidth={1 + (edge.count / maxEdge) * 6} />)}{areas.map((area, index) => <g key={area} transform={`translate(${positions[index][0]} ${positions[index][1]})`}><circle r={index === 7 ? 52 : 42} fill="hsl(var(--background))" stroke="hsl(var(--primary))" strokeWidth="2" /><text textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--foreground))" fontSize="11"><tspan x="0" dy={area.length > 18 ? "-.55em" : "0"}>{area.length > 18 ? area.split(" ").slice(0, -1).join(" ") : area}</tspan>{area.length > 18 && <tspan x="0" dy="1.2em">{area.split(" ").at(-1)}</tspan>}</text></g>)}</svg></CardContent></Card><Card><CardContent className="p-6 sm:p-7"><h3 className="font-display text-2xl">Strongest connections</h3><div className="mt-7 space-y-5">{edges.sort((left, right) => right.count - left.count).slice(0, 8).map((edge) => <div key={`${edge.left}-${edge.right}`}><p className="text-sm font-medium">{edge.left} ↔ {edge.right}</p><p className="mt-1 text-xs text-muted-foreground">{edge.count} shared publications</p></div>)}</div></CardContent></Card></div>;
}

function ResearchActivity() {
  const categoryCounts = countBy(repositories.map((repository) => repository.category));
  const releaseCounts = [["Software releases", publications.filter((publication) => publication.type === "Software").length], ["Datasets", publications.filter((publication) => publication.type === "Dataset").length], ["Patents", publications.filter((publication) => publication.type === "Patent").length], ["Open repositories", repositories.filter((repository) => !repository.archived).length]] as Array<[string, number]>;
  const current = yearCounts.at(-1)?.count ?? 0;
  const previous = yearCounts.at(-2)?.count ?? 0;
  const growth = previous ? ((current - previous) / previous) * 100 : null;
  return <div className="grid gap-5 md:grid-cols-2"><Card><CardContent className="p-6 sm:p-8"><p className="eyebrow">Research growth</p><p className="mt-5 font-display text-6xl text-primary">{growth === null ? "—" : `${growth >= 0 ? "+" : ""}${Math.round(growth)}%`}</p><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Year-over-year change from {yearCounts.at(-2)?.year ?? "the previous year"} to {yearCounts.at(-1)?.year ?? "the latest year"}, based on synchronized publication dates.</p></CardContent></Card><RankedBars title="GitHub contribution summary" data={categoryCounts} /><RankedBars title="Research outputs" data={releaseCounts} /><Card><CardContent className="p-6 sm:p-8"><h3 className="font-display text-3xl">ORCID activity</h3><p className="mt-2 text-sm text-muted-foreground">Publication records by recent year.</p><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3">{yearCounts.slice(-6).reverse().map(({ year, count }) => <div key={year} className="rounded-2xl border border-border/70 bg-background/60 p-4"><p className="font-display text-3xl text-primary">{count}</p><p className="mt-1 text-xs text-muted-foreground">{year}</p></div>)}</div></CardContent></Card></div>;
}

export function ResearchAnalytics() {
  const [view, setView] = useState<View>("overview");
  const summary = useMemo(() => ({ total: publications.length, open: publications.filter((publication) => publication.openAccess === "open").length, cited: publications.filter((publication) => publication.citationCount !== null).length }), []);
  return <section className="content-auto border-y border-border/60 bg-muted/25 py-20 sm:py-28" aria-labelledby="research-analytics-title"><div className="container"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div className="max-w-3xl"><p className="eyebrow mb-4">Interactive evidence</p><h2 id="research-analytics-title" className="font-display text-4xl tracking-tight sm:text-6xl">Research analytics</h2><p className="mt-5 text-lg leading-relaxed text-muted-foreground">Explore publication growth, research evolution, scholarly networks, and open-source activity.</p></div><div className="flex flex-wrap gap-2" role="group" aria-label="Select analytics view">{views.map(({ id, label, icon: Icon }) => <Button key={id} type="button" variant={view === id ? "default" : "outline"} size="sm" aria-pressed={view === id} onClick={() => setView(id)}><Icon aria-hidden="true" className="size-3.5" />{label}</Button>)}</div></div><div className="mt-10 grid grid-cols-3 gap-3"><div className="rounded-2xl border bg-background/60 p-4"><p className="font-display text-3xl text-primary">{summary.total}</p><p className="mt-1 text-xs text-muted-foreground">Analyzed records</p></div><div className="rounded-2xl border bg-background/60 p-4"><p className="font-display text-3xl text-primary">{summary.open}</p><p className="mt-1 text-xs text-muted-foreground">Verified open access</p></div><div className="rounded-2xl border bg-background/60 p-4"><p className="font-display text-3xl text-primary">{summary.cited}</p><p className="mt-1 text-xs text-muted-foreground">OpenAlex-enriched</p></div></div><div className="mt-5">{view === "overview" && <div className="grid gap-5 md:grid-cols-2"><Timeline /><RankedBars title="Publication types" data={typeCounts} /><RankedBars title="Research area distribution" data={areaCounts} /><RankedBars title="Top publishers" data={publisherCounts} /><RankedBars title="Top venues" data={venueCounts} /></div>}{view === "evolution" && <Evolution />}{view === "network" && <ResearchNetwork />}{view === "activity" && <ResearchActivity />}</div></div></section>;
}
