import { ArrowRight, BookOpen, CalendarDays, GraduationCap } from "lucide-react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import type { TeachingCourse } from "@/types/teaching";

export function CourseCard({ course }: { course: TeachingCourse }) {
  return <Card className="group h-full"><CardContent className="flex h-full min-h-[25rem] flex-col p-7 sm:p-8"><div className="flex items-start justify-between gap-4"><span className="grid size-11 place-items-center rounded-2xl bg-primary/10 text-primary"><GraduationCap aria-hidden="true" className="size-5" /></span><Badge className="text-primary">{course.category}</Badge></div><p className="mt-7 text-xs font-bold uppercase tracking-[.14em] text-primary">{course.code ?? "Academic offering"}</p><h3 className="mt-3 font-display text-3xl leading-tight transition-colors group-hover:text-primary">{course.title}</h3><p className="mt-4 line-clamp-4 flex-1 leading-relaxed text-muted-foreground">{course.overview}</p><dl className="mt-6 grid gap-2 border-t border-border/70 pt-5 text-sm text-muted-foreground"><div className="flex items-center gap-2"><BookOpen aria-hidden="true" className="size-4 text-primary" /><dt className="sr-only">Programme</dt><dd>{course.programme}</dd></div><div className="flex items-center gap-2"><CalendarDays aria-hidden="true" className="size-4 text-primary" /><dt className="sr-only">Academic period</dt><dd>{[course.semester, course.academicYear].filter(Boolean).join(" · ") || "Academic period awaiting verification"}</dd></div></dl><div className="mt-5 flex flex-wrap gap-2">{course.topics.slice(0, 3).map((topic) => <Badge key={topic}>{topic}</Badge>)}</div><Link href={`/teaching/${course.slug}`} className="mt-7 inline-flex w-fit items-center gap-2 text-sm font-semibold text-primary underline-offset-4 hover:underline">View course portfolio <ArrowRight aria-hidden="true" className="size-4 transition-transform group-hover:translate-x-1" /></Link></CardContent></Card>;
}
