import { ArrowLeft, ArrowUpRight, BookOpen, CalendarDays, CheckCircle2, ClipboardCheck, Download, FileQuestion, FlaskConical, GraduationCap, Lightbulb, ListChecks } from "lucide-react";
import Link from "next/link";
import { TeachingEmptyState } from "@/components/teaching/teaching-empty-state";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import type { TeachingCourse } from "@/types/teaching";

function SectionHeader({ eyebrow, title, icon: Icon }: { eyebrow: string; title: string; icon: typeof BookOpen }) {
  return <div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-primary/10 text-primary"><Icon aria-hidden="true" className="size-4" /></span><div><p className="eyebrow">{eyebrow}</p><h2 className="mt-1 font-display text-3xl sm:text-4xl">{title}</h2></div></div>;
}

const unavailable = (subject: string) => <TeachingEmptyState title={`${subject} awaiting verification`} description={`No verified ${subject.toLowerCase()} has been supplied for this course.`} />;

export function CourseDetail({ course }: { course: TeachingCourse }) {
  return <div className="space-y-20 sm:space-y-24"><Link href="/teaching" className="inline-flex items-center gap-2 text-sm font-semibold text-primary underline-offset-4 hover:underline"><ArrowLeft aria-hidden="true" className="size-4" /> Back to teaching portfolio</Link>
    <section aria-labelledby="course-overview-title"><div className="grid gap-6 lg:grid-cols-[1fr_20rem]"><div><SectionHeader eyebrow="Course overview" title="Purpose and context" icon={BookOpen} /><p id="course-overview-title" className="mt-7 max-w-3xl text-lg leading-[1.8] text-muted-foreground">{course.overview}</p><div className="mt-6 flex flex-wrap gap-2">{course.topics.map((topic) => <Badge key={topic}>{topic}</Badge>)}</div></div><Card><CardContent className="p-6"><dl className="space-y-5 text-sm">{[["Course code", course.code], ["Institution", course.institution], ["Programme", course.programme], ["Semester", course.semester], ["Academic year", course.academicYear], ["Domain", course.domain]].map(([label, value]) => <div key={label}><dt className="text-xs font-bold uppercase tracking-[.12em] text-muted-foreground">{label}</dt><dd className="mt-1.5 font-medium">{value ?? "Not yet verified"}</dd></div>)}</dl></CardContent></Card></div><div className="mt-8 rounded-2xl border border-amber-300/40 bg-amber-50 p-5 text-sm leading-relaxed text-amber-950 dark:border-amber-700/40 dark:bg-amber-950/30 dark:text-amber-100"><strong>Data provenance:</strong> {course.verificationNote}</div></section>

    <section aria-labelledby="learning-outcomes-title"><SectionHeader eyebrow="Learning design" title="Learning outcomes" icon={CheckCircle2} /><div id="learning-outcomes-title" className="mt-7">{course.learningOutcomes.length > 0 ? <ol className="grid gap-4 sm:grid-cols-2">{course.learningOutcomes.map((outcome, index) => <li key={outcome} className="rounded-2xl border border-border bg-card/60 p-5"><span className="text-xs font-bold text-primary">LO {String(index + 1).padStart(2, "0")}</span><p className="mt-2 leading-relaxed text-muted-foreground">{outcome}</p></li>)}</ol> : unavailable("Learning outcomes")}</div></section>

    <section aria-labelledby="weekly-plan-title"><SectionHeader eyebrow="Weekly teaching plan" title="Course progression" icon={CalendarDays} /><div id="weekly-plan-title" className="mt-7">{course.weeklyTeachingPlan.length > 0 ? <ol className="space-y-3">{course.weeklyTeachingPlan.map((item) => <li key={item.week} className="grid gap-3 rounded-2xl border border-border bg-card/60 p-5 sm:grid-cols-[5rem_1fr]"><span className="text-sm font-bold text-primary">Week {item.week}</span><div><h3 className="font-semibold">{item.topic}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{item.learningFocus}</p>{item.activity && <p className="mt-2 text-sm"><strong>Activity:</strong> {item.activity}</p>}</div></li>)}</ol> : unavailable("Weekly teaching plan")}</div></section>

    <section aria-labelledby="lecture-schedule-title"><SectionHeader eyebrow="Lecture schedule" title="Planned sessions" icon={ListChecks} /><div id="lecture-schedule-title" className="mt-7">{course.lectureSchedule.length > 0 ? <div className="overflow-x-auto rounded-2xl border border-border"><table className="w-full min-w-[40rem] text-left text-sm"><thead className="bg-muted/50"><tr><th className="p-4">Date</th><th className="p-4">Topic</th><th className="p-4">Format</th><th className="p-4">Status</th></tr></thead><tbody>{course.lectureSchedule.map((lecture) => <tr key={`${lecture.date}-${lecture.topic}`} className="border-t border-border"><td className="p-4">{lecture.date}</td><td className="p-4 font-medium">{lecture.topic}</td><td className="p-4 text-muted-foreground">{lecture.format}</td><td className="p-4"><Badge>{lecture.status}</Badge></td></tr>)}</tbody></table></div> : unavailable("Lecture schedule")}</div></section>

    <section aria-labelledby="course-resources-title"><SectionHeader eyebrow="Downloadable resources" title="Course library" icon={Download} /><div id="course-resources-title" className="mt-7">{course.resources.length > 0 ? <div className="grid gap-4 md:grid-cols-2">{course.resources.map((resource) => <Card key={resource.id}><CardContent className="p-6"><Badge className="text-primary">{resource.type}</Badge><h3 className="mt-4 font-display text-2xl">{resource.title}</h3>{resource.description && <p className="mt-3 text-sm leading-relaxed text-muted-foreground">{resource.description}</p>}<a href={resource.url} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline">Open resource <ArrowUpRight aria-hidden="true" className="size-4" /></a></CardContent></Card>)}</div> : unavailable("Course resources")}</div></section>

    <div className="grid gap-12 lg:grid-cols-2"><section aria-labelledby="assessment-title"><SectionHeader eyebrow="Assessment pattern" title="Evidence of learning" icon={ClipboardCheck} /><div id="assessment-title" className="mt-7">{course.assessmentPattern.length > 0 ? <ul className="space-y-3">{course.assessmentPattern.map((assessment) => <li key={assessment.component} className="rounded-2xl border border-border p-5"><div className="flex justify-between gap-4"><h3 className="font-semibold">{assessment.component}</h3><span className="text-sm font-bold text-primary">{assessment.weight === null ? "Weight pending" : `${assessment.weight}%`}</span></div><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{assessment.description}</p></li>)}</ul> : unavailable("Assessment pattern")}</div></section><section aria-labelledby="activities-title"><SectionHeader eyebrow="Class activities" title="Active learning" icon={FlaskConical} /><div id="activities-title" className="mt-7">{course.classActivities.length > 0 ? <ul className="space-y-3">{course.classActivities.map((activity) => <li key={activity} className="rounded-2xl border border-border p-5 leading-relaxed text-muted-foreground">{activity}</li>)}</ul> : unavailable("Class activities")}</div></section></div>

    <div className="grid gap-12 lg:grid-cols-2"><section aria-labelledby="project-ideas-title"><SectionHeader eyebrow="Project ideas" title="Applied exploration" icon={Lightbulb} /><div id="project-ideas-title" className="mt-7">{course.projectIdeas.length > 0 ? <ul className="space-y-3">{course.projectIdeas.map((idea) => <li key={idea} className="rounded-2xl border border-border p-5 leading-relaxed text-muted-foreground">{idea}</li>)}</ul> : unavailable("Project ideas")}</div></section><section aria-labelledby="faqs-title"><SectionHeader eyebrow="FAQs" title="Course questions" icon={FileQuestion} /><div id="faqs-title" className="mt-7">{course.faqs.length > 0 ? <div className="space-y-3">{course.faqs.map((faq) => <details key={faq.question} className="rounded-2xl border border-border p-5"><summary className="cursor-pointer font-semibold">{faq.question}</summary><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{faq.answer}</p></details>)}</div> : unavailable("Course FAQs")}</div></section></div>

    <section aria-labelledby="course-links-title"><SectionHeader eyebrow="Course access" title="Platforms and verified sources" icon={GraduationCap} /><div id="course-links-title" className="mt-7 flex flex-wrap gap-3">{course.googleClassroomUrl && <a href={course.googleClassroomUrl} target="_blank" rel="noreferrer" className="rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Google Classroom</a>}{course.courseWebsiteUrl && <a href={course.courseWebsiteUrl} target="_blank" rel="noreferrer" className="rounded-full border border-border px-5 py-3 text-sm font-semibold">Course website</a>}{course.sourceUrls.map((url, index) => <a key={url} href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-border px-5 py-3 text-sm font-semibold text-primary">Verified source {index + 1}<ArrowUpRight aria-hidden="true" className="size-4" /></a>)}</div>{!course.googleClassroomUrl && !course.courseWebsiteUrl && <p className="mt-4 text-sm text-muted-foreground">No verified Google Classroom or dedicated course website URL is currently available.</p>}</section>
  </div>;
}
