"use client";

import Fuse from "fuse.js";
import { ArrowUpRight, BriefcaseBusiness, Download, FileSearch, Filter, Search, ShieldCheck, UsersRound, X } from "lucide-react";
import { useCallback, useMemo, useState } from "react";
import { CourseCard } from "@/components/teaching/course-card";
import { TeachingAnalytics } from "@/components/teaching/teaching-analytics";
import { TeachingEmptyState } from "@/components/teaching/teaching-empty-state";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { AcademicContribution, AcademicContributionCategory, CourseCategory, StudentProject, StudentProjectCategory, TeachingCourse, TeachingMetric, TeachingResourceType } from "@/types/teaching";

type Membership = { label: string; detail: string };
type ResourceRecord = TeachingCourse["resources"][number] & { courseId: string; courseSlug: string; courseTitle: string };
type FilterValue = string | "All";

const resourceTypes: TeachingResourceType[] = ["Lecture Slides", "Syllabus", "Reading List", "Assignment", "Lab Manual", "Tutorial", "Question Bank", "Reference Book", "Video"];
const selectClass = "h-11 rounded-xl border border-border bg-background px-3 text-sm text-foreground outline-none focus:border-primary focus:ring-4 focus:ring-primary/10";

export function TeachingPortal({ courses, resources, contributions, projects, metrics, memberships, courseCategories, projectCategories, contributionCategories }: { courses: TeachingCourse[]; resources: ResourceRecord[]; contributions: AcademicContribution[]; projects: StudentProject[]; metrics: TeachingMetric[]; memberships: Membership[]; courseCategories: CourseCategory[]; projectCategories: StudentProjectCategory[]; contributionCategories: AcademicContributionCategory[] }) {
  const [query, setQuery] = useState("");
  const [courseSelection, setCourseSelection] = useState<FilterValue>("All");
  const [category, setCategory] = useState<FilterValue>("All");
  const [programme, setProgramme] = useState<FilterValue>("All");
  const [year, setYear] = useState<FilterValue>("All");
  const [semester, setSemester] = useState<FilterValue>("All");
  const [topic, setTopic] = useState<FilterValue>("All");
  const [projectCategory, setProjectCategory] = useState<FilterValue>("All");

  const programmes = useMemo(() => [...new Set(courses.map((course) => course.programme))].sort(), [courses]);
  const years = useMemo(() => [...new Set([...courses.map((course) => course.academicYear), ...projects.map((project) => project.academicYear)].filter((value): value is string => Boolean(value)))].sort().reverse(), [courses, projects]);
  const semesters = useMemo(() => [...new Set(courses.map((course) => course.semester).filter((value): value is string => Boolean(value)))].sort(), [courses]);
  const topics = useMemo(() => [...new Set(courses.flatMap((course) => course.topics))].sort(), [courses]);
  const courseFuse = useMemo(() => new Fuse(courses, { threshold: .32, ignoreLocation: true, keys: [{ name: "title", weight: 2 }, "code", "programme", "domain", "overview", "topics"] }), [courses]);
  const resourceFuse = useMemo(() => new Fuse(resources, { threshold: .32, ignoreLocation: true, keys: [{ name: "title", weight: 2 }, "courseTitle", "type", "description", "topic"] }), [resources]);

  const matchesCourseFilters = useCallback((course: TeachingCourse) => (courseSelection === "All" || course.title === courseSelection) && (category === "All" || course.category === category) && (programme === "All" || course.programme === programme) && (year === "All" || course.academicYear === year) && (semester === "All" || course.semester === semester) && (topic === "All" || course.topics.includes(topic)), [category, courseSelection, programme, semester, topic, year]);
  const filteredCourses = useMemo(() => (query.trim() ? courseFuse.search(query).map((result) => result.item) : courses).filter(matchesCourseFilters), [courseFuse, courses, matchesCourseFilters, query]);
  const filteredResources = useMemo(() => (query.trim() ? resourceFuse.search(query).map((result) => result.item) : resources).filter((resource) => { const course = courses.find((item) => item.id === resource.courseId); return course ? matchesCourseFilters(course) : false; }), [courses, matchesCourseFilters, query, resourceFuse, resources]);
  const filtersActive = Boolean(query.trim()) || [courseSelection, category, programme, year, semester, topic].some((value) => value !== "All");
  const clearFilters = () => { setQuery(""); setCourseSelection("All"); setCategory("All"); setProgramme("All"); setYear("All"); setSemester("All"); setTopic("All"); };
  const visibleProjects = projectCategory === "All" ? projects : projects.filter((project) => project.category === projectCategory);

  return <div className="space-y-24 sm:space-y-32">
    <section aria-labelledby="teaching-overview-title"><div className="grid gap-5 rounded-[2rem] bg-slate-950 p-7 text-white sm:p-10 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow text-indigo-300">Academic practice</p><h2 id="teaching-overview-title" className="mt-4 max-w-2xl font-display text-4xl leading-tight sm:text-5xl">Concepts, context, and implementation.</h2><p className="mt-5 max-w-2xl leading-[1.8] text-slate-300">A structured record of verified teaching, project-based learning, mentorship, academic service, and resources. Unverified details are deliberately marked unavailable.</p></div><div className="grid grid-cols-2 gap-3 self-end">{[{ label: "Course records", value: courses.length }, { label: "Resources", value: resources.length }, { label: "Student projects", value: projects.length }, { label: "Academic contributions", value: contributions.length }].map((item) => <div key={item.label} className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-3xl font-semibold tabular-nums">{item.value}</p><p className="mt-1 text-xs text-slate-400">{item.label}</p></div>)}</div></div></section>

    <section aria-labelledby="teaching-search-title"><div className="flex items-center gap-3"><FileSearch aria-hidden="true" className="size-5 text-primary" /><div><p className="eyebrow">Search & discovery</p><h2 id="teaching-search-title" className="mt-2 font-display text-4xl sm:text-5xl">Find courses and resources</h2></div></div><div className="mt-8 rounded-[2rem] border border-border/70 bg-card/60 p-5 shadow-sm sm:p-7"><label htmlFor="teaching-search" className="sr-only">Search teaching courses and resources</label><div className="relative"><Search aria-hidden="true" className="pointer-events-none absolute left-5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input id="teaching-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search titles, topics, programmes, domains, and teaching resources…" className="pl-12" /></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6" aria-label="Teaching filters">{[
      { label: "Course", value: courseSelection, setter: setCourseSelection, options: courses.map((course) => course.title) },
      { label: "Category", value: category, setter: setCategory, options: courseCategories },
      { label: "Programme", value: programme, setter: setProgramme, options: programmes },
      { label: "Year", value: year, setter: setYear, options: years },
      { label: "Semester", value: semester, setter: setSemester, options: semesters },
      { label: "Topic", value: topic, setter: setTopic, options: topics },
    ].map((filter) => <label key={filter.label} className="text-[.65rem] font-bold uppercase tracking-[.12em] text-muted-foreground">{filter.label}<select value={filter.value} onChange={(event) => filter.setter(event.target.value)} className={`${selectClass} mt-1 w-full`}><option>All</option>{filter.options.map((option) => <option key={option}>{option}</option>)}</select></label>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 text-sm text-muted-foreground"><span className="inline-flex items-center gap-2"><Filter aria-hidden="true" className="size-4" /> {filteredCourses.length} course{filteredCourses.length === 1 ? "" : "s"} · {filteredResources.length} resource{filteredResources.length === 1 ? "" : "s"}</span>{filtersActive && <Button type="button" variant="ghost" size="sm" onClick={clearFilters}><X aria-hidden="true" className="size-4" /> Clear filters</Button>}</div></div></section>

    <section aria-labelledby="course-catalog-title"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Courses</p><h2 id="course-catalog-title" className="mt-3 font-display text-4xl sm:text-5xl">Teaching portfolio</h2></div><div className="flex flex-wrap gap-2">{courseCategories.map((item) => <Badge key={item} className="px-3 py-2">{item} · {courses.filter((course) => course.category === item).length}</Badge>)}</div></div>{filteredCourses.length > 0 ? <div className="mt-8 grid gap-6 lg:grid-cols-2">{filteredCourses.map((course) => <CourseCard key={course.id} course={course} />)}</div> : <div className="mt-8"><TeachingEmptyState title="No matching courses" description="No verified course record matches the current search and filters. Remove a filter or try a broader topic." /></div>}</section>

    <TeachingAnalytics courses={courses} metrics={metrics} />

    <section aria-labelledby="downloads-title"><div className="flex items-center gap-3"><Download aria-hidden="true" className="size-5 text-primary" /><div><p className="eyebrow">Downloads</p><h2 id="downloads-title" className="mt-2 font-display text-4xl sm:text-5xl">Teaching resource library</h2></div></div><div className="mt-7 flex flex-wrap gap-2">{resourceTypes.map((type) => <Badge key={type}>{type} · {resources.filter((resource) => resource.type === type).length}</Badge>)}</div>{filteredResources.length > 0 ? <div className="mt-8 grid gap-4 md:grid-cols-2">{filteredResources.map((resource) => <Card key={resource.id}><CardContent className="p-6"><Badge className="text-primary">{resource.type}</Badge><h3 className="mt-4 font-display text-2xl">{resource.title}</h3><p className="mt-2 text-sm text-muted-foreground">{resource.courseTitle}{resource.topic ? ` · ${resource.topic}` : ""}</p><a href={resource.url} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary underline-offset-4 hover:underline">Open resource <ArrowUpRight aria-hidden="true" className="size-4" /></a></CardContent></Card>)}</div> : <div className="mt-8"><TeachingEmptyState title="Course files awaiting publication" description="No verified lecture slides, syllabi, reading lists, assignments, lab manuals, tutorials, question banks, reference books, or videos are currently published in the local teaching records." /></div>}</section>

    <section aria-labelledby="contributions-title"><div className="flex items-center gap-3"><ShieldCheck aria-hidden="true" className="size-5 text-primary" /><div><p className="eyebrow">Academic contributions</p><h2 id="contributions-title" className="mt-2 font-display text-4xl sm:text-5xl">Service, supervision, and leadership</h2></div></div><div className="mt-8 grid gap-4 lg:grid-cols-2">{contributionCategories.map((item) => { const records = contributions.filter((contribution) => contribution.category === item); return <Card key={item}><CardContent className="p-6 sm:p-7"><h3 className="font-display text-2xl">{item}</h3>{records.length > 0 ? <ul className="mt-5 space-y-5">{records.map((record) => <li key={record.id} className="border-t border-border/70 pt-5 first:border-0 first:pt-0"><p className="font-semibold leading-snug">{record.title}</p><p className="mt-2 text-sm text-muted-foreground">{record.organization} · {record.period}</p><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{record.description}</p><a href={record.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline">Verified source <ArrowUpRight aria-hidden="true" className="size-3" /></a></li>)}</ul> : <div className="mt-5"><TeachingEmptyState compact title="Verification pending" description={`No verified ${item.toLowerCase()} record is currently available.`} /></div>}</CardContent></Card>; })}<Card><CardContent className="p-6 sm:p-7"><h3 className="font-display text-2xl">Professional Memberships</h3><ul className="mt-5 grid gap-3 sm:grid-cols-2">{memberships.map((membership) => <li key={membership.label} className="rounded-2xl bg-muted/40 p-4"><p className="font-semibold">{membership.label}</p><p className="mt-1 text-sm text-muted-foreground">{membership.detail}</p></li>)}</ul></CardContent></Card></div></section>

    <section aria-labelledby="student-projects-title"><div className="flex items-center gap-3"><UsersRound aria-hidden="true" className="size-5 text-primary" /><div><p className="eyebrow">Student projects</p><h2 id="student-projects-title" className="mt-2 font-display text-4xl sm:text-5xl">Mentored applied work</h2></div></div><div className="mt-7 flex flex-wrap gap-2"><button type="button" aria-pressed={projectCategory === "All"} onClick={() => setProjectCategory("All")} className="rounded-full border border-border px-4 py-2 text-sm aria-pressed:border-primary/40 aria-pressed:bg-primary/10 aria-pressed:text-primary">All · {projects.length}</button>{projectCategories.map((item) => <button key={item} type="button" aria-pressed={projectCategory === item} onClick={() => setProjectCategory(item)} className="rounded-full border border-border px-4 py-2 text-sm aria-pressed:border-primary/40 aria-pressed:bg-primary/10 aria-pressed:text-primary">{item} · {projects.filter((project) => project.category === item).length}</button>)}</div>{visibleProjects.length > 0 ? <div className="mt-8 grid gap-6 lg:grid-cols-2">{visibleProjects.map((project) => <Card key={project.id}><CardContent className="p-7"><div className="flex items-center justify-between gap-4"><Badge className="text-primary">{project.category}</Badge><span className="text-xs text-muted-foreground">{project.academicYear}</span></div><BriefcaseBusiness aria-hidden="true" className="mt-7 size-5 text-primary" /><h3 className="mt-4 font-display text-3xl">{project.title}</h3><p className="mt-4 leading-relaxed text-muted-foreground">{project.abstract}</p>{project.technologies.length > 0 && <div className="mt-5 flex flex-wrap gap-2">{project.technologies.map((technology) => <Badge key={technology}>{technology}</Badge>)}</div>}<div className="mt-6 flex flex-wrap gap-4 text-sm">{[["GitHub", project.githubUrl], ["Report", project.reportUrl], ["Presentation", project.presentationUrl]].filter((entry): entry is [string, string] => Boolean(entry[1])).map(([label, url]) => <a key={label} href={url} target="_blank" rel="noreferrer" className="font-semibold text-primary hover:underline">{label}</a>)}<a href={project.sourceUrl} target="_blank" rel="noreferrer" className="font-semibold text-primary hover:underline">Verified source</a></div></CardContent></Card>)}</div> : <div className="mt-8"><TeachingEmptyState title="No verified projects in this category" description="Project abstracts, technology stacks, repositories, reports, and presentations will appear after faculty verification." /></div>}</section>
  </div>;
}
