import type { Metadata } from "next";
import { GraduationCap } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { ContentSection, PageShell } from "@/components/page-shell";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { courses, profile } from "@/lib/content";
import { createPageMetadata } from "@/lib/metadata";

export const metadata: Metadata = createPageMetadata({ title: "Teaching & Mentorship", description: "Teaching, academic mentorship, and supervision areas of Mohit Tiwari at BVCOE New Delhi.", path: "/teaching" });

export default function TeachingPage() {
  return <PageShell><PageHero eyebrow="Teaching & mentorship" title="Engineering learning through research." description="Teaching connects computing fundamentals with secure systems, reproducible experimentation, and real engineering contexts." icon={GraduationCap} /><ContentSection><section aria-labelledby="teaching-principles" className="mb-16 grid gap-5 rounded-3xl bg-slate-950 p-8 text-white sm:grid-cols-[.7fr_1.3fr] sm:p-10"><div><p className="eyebrow text-indigo-300">Academic practice</p><h2 id="teaching-principles" className="mt-4 font-display text-4xl">Concepts, context, and implementation.</h2></div><p className="leading-[1.8] text-slate-300">Students are encouraged to connect theoretical foundations with security, systems design, experimental evidence, and responsible software practice.</p></section>{courses.length > 0 ? <div className="grid gap-6 lg:grid-cols-3">{courses.map((course) => <Card key={course.code} className="h-full"><CardContent className="flex min-h-96 flex-col p-7"><GraduationCap aria-hidden="true" className="size-6 text-primary" /><p className="mt-8 text-sm font-bold text-primary">{course.code} · {course.level}</p><h2 className="mt-3 font-display text-3xl">{course.title}</h2><p className="mt-4 flex-1 leading-relaxed text-muted-foreground">{course.description}</p><div className="mt-6 flex flex-wrap gap-2">{course.topics.map((topic) => <Badge key={topic}>{topic}</Badge>)}</div><p className="mt-6 border-t border-border pt-5 text-sm text-muted-foreground">{course.term}</p></CardContent></Card>)}</div> : <section aria-labelledby="supervision-areas"><p className="eyebrow">Supervision areas</p><h2 id="supervision-areas" className="mt-4 font-display text-4xl sm:text-5xl">Research-led student work</h2><p className="mt-5 max-w-2xl leading-[1.75] text-muted-foreground">Verified course details have not yet been added. Academic project and research supervision aligns with the following declared research areas.</p><div className="mt-8 flex flex-wrap gap-3">{profile.researchAreas.map((area) => <Badge key={area} className="px-4 py-2 text-sm">{area}</Badge>)}</div></section>}</ContentSection></PageShell>;
}
